### ISSUE TITLE
Remove 'distribute' from the setup.py requirements

### ISSUE THREAD

**Issue by b-a-t** [klinkin/pyunisend#5]
Hi, Mikhail!

Basically, any attempt to build the module with the modern tools fails with:

```
  Running setup.py bdist_wheel for distribute: started
  Running setup.py bdist_wheel for distribute: finished with status 'error'
  Complete output from command /srv/env/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xugqIZ/distribute/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpzmJYLRpip-wheel- --python-tag cp27:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-xugqIZ/distribute/setup.py", line 58, in <module>
      setuptools.setup(**setup_params)
    File "/usr/lib/python2.7/distutils/core.py", line 137, in setup
      ok = dist.parse_command_line()
    File "setuptools/dist.py", line 276, in parse_command_line
      result = _Distribution.parse_command_line(self)
    File "/usr/lib/python2.7/distutils/dist.py", line 467, in parse_command_line
      args = self._parse_command_opts(parser, args)
    File "setuptools/dist.py", line 602, in _parse_command_opts
      nargs = _Distribution._parse_command_opts(self, parser, args)
    File "/usr/lib/python2.7/distutils/dist.py", line 523, in _parse_command_opts
      cmd_class = self.get_command_class(command)
    File "setuptools/dist.py", line 406, in get_command_class
      ep.require(installer=self.fetch_build_egg)
    File "pkg_resources.py", line 2254, in require
      working_set.resolve(self.dist.requires(self.extras),env,installer)))
    File "pkg_resources.py", line 2471, in requires
      dm = self._dep_map
    File "pkg_resources.py", line 2682, in _dep_map
      self.__dep_map = self._compute_dependencies()
    File "pkg_resources.py", line 2699, in _compute_dependencies
      from _markerlib import compile as compile_marker
  ImportError: No module named _markerlib

  ----------------------------------------
.[91m  Failed building wheel for distribute
.[0m  Running setup.py clean for distribute
```

Distribute is ancient and outdated and similar projects removed it from the dependencies, see:
[Running setup.py bdist_wheel for 'distribute' fails](https://github.com/ovh/djehouty/issues/7) and [distribute wheel build failure in setuptools>=20.2](https://github.com/pypa/setuptools/issues/535)

**Comment by maxclax** [comment]
Deleted on last commit and change python 2 to 3
